package com.sample
 
import com.sample.model.Person;

declare Test
	name : String
end

rule "Wage"
no-loop true
when
	$person : Person(hourlyRate*wage > 100, name : firstName, surname : lastName)
then
	$person.setFirstName(name + "my");
	$person.setLastName("Henderson");
	update($person);
	//Test test = new Test();
	//test.setName("Gio");
	//insertLogical(test);

	System.out.println( "Hello" + " " + name + " " + surname + "!");
	System.out.println( "You are rich!" );
end

rule "Change name"
when
	$person : Person (name : firstName == "Tommy")
then
	Test test = new Test();
	test.setName("Gio");
	insertLogical(test);
end	